# Generated by Django 5.2.6 on 2025-09-17 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Strategies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('trade_date', models.DateTimeField()),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='paper_trader.strategy')),
            ],
            options={
                'ordering': ['-trade_date'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(choices=[('RSI', 'Relative Strength Index'), ('SMA', 'Simple Moving Average Crossover'), ('MACD', 'MACD Signal Cross')], max_length=20)),
                ('operator', models.CharField(choices=[('gt', 'is greater than'), ('lt', 'is less than'), ('cross_above', 'crosses above')], max_length=20)),
                ('value', models.FloatField(help_text='The value to compare the indicator against.')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='paper_trader.strategy')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('strategy', 'indicator', 'operator', 'value'), name='unique_rule_per_strategy')],
            },
        ),
    ]
